(in-package "CL-USER")

(format t "~%=== Test 1: basic fiber creation ===~%")
(let* ((result nil)
       (fiber (sb-thread:make-fiber (lambda () (setf result 42))
                          :name "test-fiber"))
       (sched (sb-thread:make-fiber-scheduler)))
  (sb-thread:submit-fiber sched fiber)
  (sb-thread:run-fiber-scheduler sched)
  (assert (eql result 42))
  (assert (eq (sb-thread:fiber-state fiber) :dead))
  (format t "PASSED~%"))

(format t "~%=== Test 2: return value ===~%")
(let* ((fiber (sb-thread:make-fiber (lambda () (+ 1 2 3))
                          :name "return-value-fiber"))
       (sched (sb-thread:make-fiber-scheduler)))
  (sb-thread:submit-fiber sched fiber)
  (sb-thread:run-fiber-scheduler sched)
  (assert (eql (sb-thread:fiber-result fiber) 6))
  (format t "PASSED~%"))

(format t "~%=== Test 3: multiple fibers ===~%")
(let* ((results nil)
       (sched (sb-thread:make-fiber-scheduler)))
  (dotimes (i 5)
    (let ((n i))
      (sb-thread:submit-fiber sched
                    (sb-thread:make-fiber (lambda () (push n results))
                                :name (format nil "fiber-~D" n)))))
  (sb-thread:run-fiber-scheduler sched)
  (assert (= (length results) 5))
  (assert (null (set-difference results '(0 1 2 3 4))))
  (format t "PASSED~%"))

(format t "~%=== Test 4: yield and resume ===~%")
(let* ((log nil)
       (sched (sb-thread:make-fiber-scheduler)))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (push 'a1 log)
                              (sb-thread:fiber-yield)
                              (push 'a2 log))
                            :name "fiber-a"))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (push 'b1 log)
                              (sb-thread:fiber-yield)
                              (push 'b2 log))
                            :name "fiber-b"))
  (sb-thread:run-fiber-scheduler sched)
  (format t "Log: ~A~%" log)
  (assert (= (length log) 4))
  (assert (member 'a1 log))
  (assert (member 'a2 log))
  (assert (member 'b1 log))
  (assert (member 'b2 log))
  (format t "PASSED~%"))

(format t "~%=== Test 5: dynamic bindings ===~%")
(defvar *fiber-test-var* :carrier-value)
(let* ((values nil)
       (sched (sb-thread:make-fiber-scheduler)))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (let ((*fiber-test-var* :fiber-a))
                                (push (cons 'a1 *fiber-test-var*) values)
                                (sb-thread:fiber-yield)
                                (push (cons 'a2 *fiber-test-var*) values)))
                            :name "binding-fiber-a"))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (let ((*fiber-test-var* :fiber-b))
                                (push (cons 'b1 *fiber-test-var*) values)
                                (sb-thread:fiber-yield)
                                (push (cons 'b2 *fiber-test-var*) values)))
                            :name "binding-fiber-b"))
  (sb-thread:run-fiber-scheduler sched)
  (format t "Values: ~A~%" values)
  (assert (equal (cdr (assoc 'a1 values)) :fiber-a))
  (assert (equal (cdr (assoc 'a2 values)) :fiber-a))
  (assert (equal (cdr (assoc 'b1 values)) :fiber-b))
  (assert (equal (cdr (assoc 'b2 values)) :fiber-b))
  (assert (eq *fiber-test-var* :carrier-value))
  (format t "PASSED~%"))

(format t "~%=== Test 6: pinned fiber refuses to yield ===~%")
(let* ((error-caught nil)
       (sched (sb-thread:make-fiber-scheduler)))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (sb-thread:fiber-pin)
                              (handler-case
                                  (sb-thread:fiber-yield)
                                (error () (setf error-caught t)))
                              (sb-thread:fiber-unpin))
                            :name "pinned-fiber"))
  (sb-thread:run-fiber-scheduler sched)
  (assert error-caught)
  (format t "PASSED~%"))

(format t "~%=== Test 7: error handling ===~%")
(let* ((sched (sb-thread:make-fiber-scheduler))
       (good-result nil))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (error "intentional fiber error"))
                            :name "error-fiber"))
  (sb-thread:submit-fiber sched
                (sb-thread:make-fiber (lambda ()
                              (setf good-result t))
                            :name "good-fiber"))
  (sb-thread:run-fiber-scheduler sched)
  (assert good-result)
  (format t "PASSED~%"))

(format t "~%=== Test 8: many fibers (stress) ===~%")
(let* ((counter 0)
       (sched (sb-thread:make-fiber-scheduler)))
  (dotimes (i 1000)
    (sb-thread:submit-fiber sched
                  (sb-thread:make-fiber (lambda ()
                                (incf counter)
                                (sb-thread:fiber-yield)
                                (incf counter)))))
  (sb-thread:run-fiber-scheduler sched)
  (assert (= counter 2000))
  (format t "PASSED (counter=~D)~%" counter))

(format t "~%=== All fiber tests PASSED ===~%")
(sb-ext:exit :code 0)
